# -*- coding: utf-8 -*-
"""CodeAlpha_EDA_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-43HVwQko2KfGZ0Ub-W4zNTUX4HgzBe
"""

# CodeAlpha Task 2: Exploratory Data Analysis
# Smartphone Dataset

import numpy as np
import pandas as pd

data = pd.read_excel("smartphones.xlsx")

print("Rows and Columns:", data.shape)

print("\nFirst 5 Rows:")
print(data.head())

#basic data structure
print(data.columns)

print("\nData Types:")
print(data.dtypes)

print("\nDataset Info:")
print(data.info())

print("\nBasic Statistical Summary:")
print(data.describe())

# What i am finding
print("1. Which smartphone brands have the most models?")
print("2. What is the price distribution of smartphones?")
print("3. Which price segment has the best average rating?")
print("4. Are 5G phones more expensive and better rated than non-5G phones?")
print("5. Which features are most related to rating?")
print("6. Which phones provide the best value for money?")

print("\nDuplicate Rows:")
print(data.duplicated().sum())

missing_values = pd.DataFrame({
    "missing_values": data.isnull().sum(),
    "missing_percent": (data.isnull().sum() / len(data) * 100).round(2)
})

print("\nMissing Values:")
print(missing_values)

df = data.copy()

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("\nCleaned Column Names:")
print(df.columns)

df["price"] = (
    df["price"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["price"] = pd.to_numeric(df["price"], errors="coerce")
print(df["price"])

df["brand"] = df["model"].astype(str).str.split().str[0]
df['brand']

df["is_5g"] = df["sim"].astype(str).str.contains("5G", case=False, na=False)

df["ram_gb"] = pd.to_numeric(
    df["ram"].astype(str).str.extract(r"(\d+)\s*GB\s*RAM")[0],
    errors="coerce"
)

gb_storage = pd.to_numeric(
    df["ram"].astype(str).str.extract(r"(\d+)\s*GB\s*inbuilt")[0],
    errors="coerce"
)

tb_storage = pd.to_numeric(
    df["ram"].astype(str).str.extract(r"(\d+)\s*TB\s*inbuilt")[0],
    errors="coerce"
) * 1024

df["storage_gb"] = gb_storage.fillna(tb_storage)

df["battery_mah"] = pd.to_numeric(
    df["battery"].astype(str).str.extract(r"(\d+)\s*mAh")[0],
    errors="coerce"
)

df["charging_watt"] = pd.to_numeric(
    df["battery"].astype(str).str.extract(r"(\d+)W")[0],
    errors="coerce"
)

df["display_inches"] = pd.to_numeric(
    df["display"].astype(str).str.extract(r"(\d+\.?\d*)\s*inches")[0],
    errors="coerce"
)

df["refresh_rate_hz"] = pd.to_numeric(
    df["display"].astype(str).str.extract(r"(\d+)\s*Hz")[0],
    errors="coerce"
)

df["rear_camera_mp"] = pd.to_numeric(
    df["camera"].astype(str).str.extract(r"(\d+\.?\d*)\s*MP")[0],
    errors="coerce"
)

df["front_camera_mp"] = pd.to_numeric(
    df["camera"].astype(str).str.extract(r"&\s*(\d+\.?\d*)\s*MP\s*Front")[0],
    errors="coerce"
)

df["card_supported"] = ~df["card"].astype(str).str.contains(
    "Not Supported",
    case=False,
    na=False
)

df["android_version"] = pd.to_numeric(
    df["os"].astype(str).str.extract(r"Android\s*v(\d+)")[0],
    errors="coerce"
)

df["price_segment"] = pd.cut(
    df["price"],
    bins=[0, 10000, 20000, 30000, 50000, 100000, np.inf],
    labels=[
        "Below 10k",
        "10k-20k",
        "20k-30k",
        "30k-50k",
        "50k-100k",
        "100k+"
    ]
)

print("\nData After Feature Extraction:")
print(df.head())

#top brands
brand_counts = df["brand"].value_counts().head(10)

print("\nTop 10 Brands by Number of Models:")
print(brand_counts)

print("\nPrice Distribution:")
print(df["price"].describe().round(2))

print("\nCheapest Phones:")
print(df[["model", "brand", "price", "rating"]].sort_values("price").head(10))

print("\nMost Expensive Phones:")
print(df[["model", "brand", "price", "rating"]].sort_values("price", ascending=False).head(10))

segment_summary = df.groupby("price_segment", observed=False).agg(
    models=("model", "count"),
    average_price=("price", "mean"),
    median_price=("price", "median"),
    average_rating=("rating", "mean"),
    median_rating=("rating", "median")
).round(2)

print("\nPrice Segment Summary:")
print(segment_summary)

network_summary = df.groupby("is_5g").agg(
    models=("model", "count"),
    average_price=("price", "mean"),
    median_price=("price", "median"),
    average_rating=("rating", "mean"),
    average_ram=("ram_gb", "mean"),
    average_storage=("storage_gb", "mean")
).round(2)

network_summary.index = ["Non-5G", "5G"]

print("\n5G vs Non-5G Summary:")
print(network_summary)

numeric_columns = [
    "price",
    "rating",
    "ram_gb",
    "storage_gb",
    "battery_mah",
    "charging_watt",
    "display_inches",
    "refresh_rate_hz",
    "rear_camera_mp",
    "front_camera_mp"
]

correlation_with_rating = (
    df[numeric_columns]
    .corr(numeric_only=True)["rating"]
    .sort_values(ascending=False)
    .round(3)
)

print("\nCorrelation With Rating:")
print(correlation_with_rating)

df["value_score"] = (df["rating"] / df["price"]) * 100000

best_value = (
    df.dropna(subset=["value_score", "rating", "price"])
    .sort_values("value_score", ascending=False)
)

print("\nTop 10 Best Value for Money Phones:")
print(
    best_value[
        [
            "model",
            "brand",
            "price",
            "rating",
            "ram_gb",
            "storage_gb",
            "is_5g",
            "value_score"
        ]
    ].head(10).round(2)
)

#  ANOMALY DETECTION
low_limit = df["price"].quantile(0.01)
high_limit = df["price"].quantile(0.99)

anomalies = df[
    (df["price"] < low_limit) |
    (df["price"] > high_limit)
]

print("\nPrice Anomalies:")
print(
    anomalies[
        ["model", "brand", "price", "rating"]
    ].sort_values("price", ascending=False)
)

# BRAND RATING ANALYSIS
brand_rating = df.groupby("brand").agg(
    models=("model", "count"),
    average_rating=("rating", "mean"),
    average_price=("price", "mean")
).round(2)

brand_rating = brand_rating[brand_rating["models"] >= 10]
brand_rating = brand_rating.sort_values("average_rating", ascending=False)

print("\nTop Brands by Average Rating:")
print(brand_rating.head(10))

#  PROCESSOR FAMILY ANALYSIS
conditions = [
    df["processor"].astype(str).str.contains("Snapdragon", case=False, na=False),
    df["processor"].astype(str).str.contains("Dimensity", case=False, na=False),
    df["processor"].astype(str).str.contains("Exynos", case=False, na=False),
    df["processor"].astype(str).str.contains("Bionic", case=False, na=False),
    df["processor"].astype(str).str.contains("Helio", case=False, na=False),
    df["processor"].astype(str).str.contains("Unisoc", case=False, na=False)
]

choices = [
    "Snapdragon",
    "Dimensity",
    "Exynos",
    "Bionic",
    "Helio",
    "Unisoc"
]

df["processor_family"] = np.select(
    conditions,
    choices,
    default="Other"
)

processor_summary = df.groupby("processor_family").agg(
    models=("model", "count"),
    average_price=("price", "mean"),
    average_rating=("rating", "mean")
).round(2)

processor_summary = processor_summary.sort_values("models", ascending=False)

print("\nProcessor Family Summary:")
print(processor_summary)

# 19. FINAL INSIGHTS

print("\nFinal Insights:")
print("1. Dataset has useful smartphone information for EDA.")
print("2. Missing values exist in some columns, especially rating.")
print("3. Samsung, Xiaomi, Vivo, Realme, and OPPO have many models.")
print("4. Price has a wide range, so median price is more reliable than mean price.")
print("5. 5G phones are generally more expensive and have better specifications.")
print("6. Rating is more related to storage, RAM, charging speed, refresh rate, and camera features.")
print("7. Some very high and very low prices should be checked before advanced analysis.")
print("8. Value score helps find budget-friendly phones, but it should not be the only decision factor.")

df.to_csv("CodeAlpha_Task2_Cleaned_Smartphones.csv", index=False)

# EDA VISUALIZATION USING MATPLOTLIB
import matplotlib.pyplot as plt

# TOP 10 BRANDS BY NUMBER OF MODELS
top_brands = df["brand"].value_counts().head(10)

plt.figure(figsize=(10, 6))
plt.bar(top_brands.index, top_brands.values)
plt.title("Top 10 Smartphone Brands by Number of Models")
plt.xlabel("Brand")
plt.ylabel("Number of Models")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# PRICE DISTRIBUTION
plt.figure(figsize=(10, 6))
plt.hist(df["price"].dropna(), bins=30)
plt.title("Smartphone Price Distribution")
plt.xlabel("Price")
plt.ylabel("Number of Phones")
plt.tight_layout()
plt.show()

# AVERAGE RATING BY PRICE SEGMENT

avg_rating_segment = df.groupby("price_segment", observed=False)["rating"].mean()

plt.figure(figsize=(10, 6))
plt.bar(avg_rating_segment.index.astype(str), avg_rating_segment.values)
plt.title("Average Rating by Price Segment")
plt.xlabel("Price Segment")
plt.ylabel("Average Rating")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# NUMBER OF PHONES IN EACH PRICE SEGMENT
price_segment_count = df["price_segment"].value_counts().sort_index()

plt.figure(figsize=(10, 6))
plt.bar(price_segment_count.index.astype(str), price_segment_count.values)
plt.title("Number of Phones in Each Price Segment")
plt.xlabel("Price Segment")
plt.ylabel("Number of Phones")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 5G VS NON-5G PHONE COUNT
network_count = df["is_5g"].value_counts()
network_labels = ["5G" if x == True else "Non-5G" for x in network_count.index]

plt.figure(figsize=(7, 5))
plt.bar(network_labels, network_count.values)
plt.title("5G vs Non-5G Phone Count")
plt.xlabel("Network Type")
plt.ylabel("Number of Phones")
plt.tight_layout()
plt.show()

#  AVERAGE PRICE: 5G VS NON-5G
avg_price_network = df.groupby("is_5g")["price"].mean()
network_labels = ["Non-5G", "5G"]

plt.figure(figsize=(7, 5))
plt.bar(network_labels, avg_price_network.values)
plt.title("Average Price: 5G vs Non-5G Phones")
plt.xlabel("Network Type")
plt.ylabel("Average Price")
plt.tight_layout()
plt.show()

# AVERAGE RATING: 5G VS NON-5G
avg_rating_network = df.groupby("is_5g")["rating"].mean()

plt.figure(figsize=(7, 5))
plt.bar(network_labels, avg_rating_network.values)
plt.title("Average Rating: 5G vs Non-5G Phones")
plt.xlabel("Network Type")
plt.ylabel("Average Rating")
plt.tight_layout()
plt.show()

# PRICE VS RATING SCATTER PLOT
plt.figure(figsize=(10, 6))
plt.scatter(df["price"], df["rating"])
plt.title("Price vs Rating")
plt.xlabel("Price")
plt.ylabel("Rating")
plt.tight_layout()
plt.show()

# CAPACITY DISTRIBUTION
plt.figure(figsize=(10, 6))
plt.hist(df["battery_mah"].dropna(), bins=25)
plt.title("Battery Capacity Distribution")
plt.xlabel("Battery Capacity mAh")
plt.ylabel("Number of Phones")
plt.tight_layout()
plt.show()

#  TOP 10 BRANDS BY AVERAGE RATING
brand_rating = df.groupby("brand").agg(
    models=("model", "count"),
    average_rating=("rating", "mean")
)

brand_rating = brand_rating[brand_rating["models"] >= 10]
brand_rating = brand_rating.sort_values("average_rating", ascending=False).head(10)

plt.figure(figsize=(10, 6))
plt.bar(brand_rating.index, brand_rating["average_rating"])
plt.title("Top 10 Brands by Average Rating")
plt.xlabel("Brand")
plt.ylabel("Average Rating")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#  TOP 10 BRANDS BY AVERAGE PRICE
brand_price = df.groupby("brand").agg(
    models=("model", "count"),
    average_price=("price", "mean")
)

brand_price = brand_price[brand_price["models"] >= 10]
brand_price = brand_price.sort_values("average_price", ascending=False).head(10)

plt.figure(figsize=(10, 6))
plt.bar(brand_price.index, brand_price["average_price"])
plt.title("Top 10 Brands by Average Price")
plt.xlabel("Brand")
plt.ylabel("Average Price")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 16. PROCESSOR FAMILY COUNT
processor_count = df["processor_family"].value_counts()

plt.figure(figsize=(10, 6))
plt.bar(processor_count.index, processor_count.values)
plt.title("Processor Family Count")
plt.xlabel("Processor Family")
plt.ylabel("Number of Phones")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#  VALUE FOR MONEY TOP 10 PHONES
top_value = df.dropna(subset=["value_score"]).sort_values(
    "value_score",
    ascending=False
).head(10)

plt.figure(figsize=(12, 6))
plt.bar(top_value["model"], top_value["value_score"])
plt.title("Top 10 Value for Money Phones")
plt.xlabel("Phone Model")
plt.ylabel("Value Score")
plt.xticks(rotation=75)
plt.tight_layout()
plt.show()

# MISSING VALUES VISUALIZATION
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]

plt.figure(figsize=(10, 6))
plt.bar(missing_values.index, missing_values.values)
plt.title("Missing Values by Column")
plt.xlabel("Columns")
plt.ylabel("Missing Values Count")
plt.xticks(rotation=75)
plt.tight_layout()
plt.show()